### ISSUE TITLE
questions: about  ClapprPlugins.Plugins

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr-plugins#18]
I see that, currently, [ClapprPlugins.Plugins](https://github.com/clappr/clappr-plugins/blob/9d2ee0f0bf246328eb63d4f98e16bb01f145ff81/src/main.js#L24) is an object.

The current Clappr Player `plugins` option expects an array. Does that mean it will accept an object instead in the future ?

For example, current workaround in my test i use is :

```javascript
// Assuming Clappr is @clappr core 0.4.x
var player = new Clappr.Player({
  // ....
  plugins: Object.values(ClapprPlugins.Plugins)
});
```

Or does the exposed ClapprPlugins.Plugins serve another purpose ? (or will be another usage methodology ?)

Or maybe it should be an Array ? :

```javascript
// Assuming Clappr is @clappr core 0.4.x
var player = new Clappr.Player({
  // ....
  plugins: ClapprPlugins.Plugins, // Assuming const Plugins = [ClickToPause, .... ]
});
```

**Comment by joaopaulovieira** [comment]
We don't think about changing the input format of option plugins at the moment, @kslimani. The `ClapprPlugins.Plugins` object was made thinking more about facilitate the bundles build for `@clappr/player`.

I think most of the time, whoever is going to use this project will want to import specific plugins and not import them all and instantiate them all because we already have the `@clappr/player` for this bundle case.

But sure, if someone has this necessity to replicate what the `@clappr/player` does, it will need to use the `ClapprPlugins.Plugins` as your example.

If necessary in the future, we can rethink this use.
