### ISSUE TITLE
Import trouble

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr-plugins#27]
I installed _@clappr/plugins_ in my _MediaControl_ extention project built with webpack, then import _MediaControl_ like that:
`import { MediaControl } from '@clappr/plugins'`
Please tell me why the project does not start after this?

> ERROR in ./node_modules/@clappr/plugins/dist/clappr-plugins.esm.js
Module not found: Error: Can't resolve '@clappr/core' in '/Users/aleksandr/projects/clappr-styling/node_modules/@clappr/plugins/dist'
 @ ./node_modules/@clappr/plugins/dist/clappr-plugins.esm.js 1:0-152

**Comment by joaopaulovieira** [comment]
**TL;DL**: Installing `clappr-core` solve your problem (:

Hello @sapolio, the Webpack log already tells you how to solve this. Any Clappr plugin extends from a base class of the `clappr-core` project. That's why we define the `clappr-core` package as a peer dependency [here](https://github.com/clappr/clappr-plugins/blob/master/package.json#L37).
